import type {
  Crisis,
  DonorProfile,
  NGOProfile,
  ResourceNeed,
  ResourcePledge,
  VolunteerProfile,
} from "@/types";

export const demoCrises: Crisis[] = [
  {
    id: "demo-vikas-nagar-fire-relief",
    title: "Vikas Nagar Fire Relief",
    type: "fire",
    summary:
      "A dense neighborhood fire in Lucknow requiring camp setup, medicine runs, and family support.",
    description:
      "A late-night residential fire in Vikas Nagar displaced dozens of families. The response room is coordinating food, clothes, blankets, medicines, and temporary shelter for affected households.",
    location: {
      lat: 26.8907,
      lng: 80.9608,
      address: "Vikas Nagar relief camp, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    riskLevel: "yellow",
    needs: ["food", "clothes", "blankets", "medicines", "shelter"],
    urgentNeeds: ["food", "blankets", "medicines", "shelter"],
    requiredResources: [
      "food packets",
      "clothes",
      "blankets",
      "medicines",
      "temporary shelter kits",
    ],
    suggestedSkills: [
      "first-aid",
      "camp coordination",
      "food distribution",
      "family registration",
    ],
    familiesAffected: 136,
    matchedVolunteers: 11,
    openTasks: 4,
    contactPerson: "Asha Verma",
    createdBy: "demo-ngo-rahat-seva-trust",
    createdAt: "2026-04-18T09:00:00.000Z",
    updatedAt: "2026-04-20T10:10:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-kerala-flood-relief",
    title: "Kerala Flood Relief",
    type: "flood",
    summary:
      "Flood corridor response near Aluva focused on rescue boats, shelter logistics, and public health supplies.",
    description:
      "Heavy river overflow has isolated multiple low-lying pockets near Aluva. The room is prioritizing boats, fishermen, swimmers, life jackets, dry food, ORS, and shelter coordination.",
    location: {
      lat: 10.1115,
      lng: 76.3484,
      address: "Riverbank support corridor, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    riskLevel: "red",
    needs: [
      "boats",
      "fishermen",
      "swimmers",
      "life jackets",
      "dry food",
      "ORS",
      "shelter",
    ],
    urgentNeeds: ["boats", "life jackets", "dry food", "ORS", "shelter"],
    requiredResources: [
      "rescue boats",
      "life jackets",
      "dry food packs",
      "ORS",
      "medical kits",
      "temporary shelter units",
    ],
    suggestedSkills: [
      "water rescue",
      "boat handling",
      "first-aid",
      "Malayalam support",
    ],
    familiesAffected: 364,
    matchedVolunteers: 14,
    openTasks: 5,
    contactPerson: "Joseph Mathew",
    createdBy: "demo-ngo-kerala-river-relief",
    createdAt: "2026-04-17T14:30:00.000Z",
    updatedAt: "2026-04-20T09:35:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-hill-landslide-relief",
    title: "Hill Landslide Relief",
    type: "landslide",
    summary:
      "A mountain access response around Mandi coordinating safe transport, guides, ropes, and medical relay.",
    description:
      "A hillside collapse blocked the main road into a small settlement above Mandi. The response is prioritizing 4x4 vehicles, ropes, first-aid, local guides, and medical transport under supervised conditions.",
    location: {
      lat: 31.7118,
      lng: 76.9317,
      address: "Upper slope access road, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    riskLevel: "yellow",
    needs: ["4x4 vehicles", "ropes", "first-aid", "local guides", "medical transport"],
    urgentNeeds: ["4x4 vehicles", "ropes", "first-aid", "medical transport"],
    requiredResources: [
      "4x4 vehicles",
      "rope kits",
      "first-aid kits",
      "medical transport slots",
      "flashlights",
    ],
    suggestedSkills: [
      "terrain driving",
      "local guidance",
      "first-aid",
      "logistics coordination",
    ],
    familiesAffected: 88,
    matchedVolunteers: 8,
    openTasks: 3,
    contactPerson: "Meera Thakur",
    createdBy: "demo-ngo-mountain-aid-network",
    createdAt: "2026-04-16T06:45:00.000Z",
    updatedAt: "2026-04-20T08:20:00.000Z",
    status: "stabilizing",
    verified: true,
  },
];

export const demoNGOProfiles: NGOProfile[] = [
  {
    id: "demo-ngo-rahat-seva-trust",
    organizationName: "Rahat Seva Trust",
    registrationNumber: "RST-LKO-2024-118",
    focusAreas: ["fire relief", "camp support", "family registration"],
    contactName: "Asha Verma",
    email: "ops@rahatseva-demo.org",
    phone: "+91 90000 11001",
    verificationDocument: "Demo verification document placeholder",
    location: {
      lat: 26.8907,
      lng: 80.9608,
      address: "Lucknow response desk, Vikas Nagar",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    createdAt: "2026-04-10T08:00:00.000Z",
    updatedAt: "2026-04-20T10:05:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-ngo-kerala-river-relief",
    organizationName: "Kerala River Relief Collective",
    registrationNumber: "KRRC-ALV-2023-204",
    focusAreas: ["flood response", "boat coordination", "shelter logistics"],
    contactName: "Joseph Mathew",
    email: "control@krrc-demo.org",
    phone: "+91 90000 11002",
    verificationDocument: "Demo verification document placeholder",
    location: {
      lat: 10.1115,
      lng: 76.3484,
      address: "Aluva river response hub",
      city: "Aluva",
      state: "Kerala",
    },
    createdAt: "2026-04-09T09:20:00.000Z",
    updatedAt: "2026-04-20T09:30:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-ngo-mountain-aid-network",
    organizationName: "Mountain Aid Network",
    registrationNumber: "MAN-MND-2022-072",
    focusAreas: ["landslide support", "terrain logistics", "medical relay"],
    contactName: "Meera Thakur",
    email: "field@mountainaid-demo.org",
    phone: "+91 90000 11003",
    verificationDocument: "Demo verification document placeholder",
    location: {
      lat: 31.7118,
      lng: 76.9317,
      address: "Mandi slope response base",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    createdAt: "2026-04-08T07:10:00.000Z",
    updatedAt: "2026-04-20T08:15:00.000Z",
    status: "active",
    verified: true,
  },
];

export const demoVolunteerProfiles: VolunteerProfile[] = [
  {
    id: "demo-vol-aarav-srivastava",
    role: "volunteer",
    userId: "demo-user-aarav-srivastava",
    name: "Aarav Srivastava",
    roleTitle: "Student volunteer",
    email: "aarav.srivastava.demo@example.org",
    phone: "+91 91000 20001",
    city: "Lucknow",
    location: {
      lat: 26.8874,
      lng: 80.9528,
      address: "Indira Nagar student hostel, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    skills: ["crowd support", "food distribution", "camp registration"],
    assets: ["bike"],
    languages: ["Hindi", "English"],
    availability: "available_now",
    availableTime: "Daily after 11 AM",
    emergencyAvailable: true,
    emergencyRadiusKm: 18,
    distanceKm: 2.2,
    responseRate: "89%",
    completedTasks: 2,
    createdAt: "2026-04-01T09:00:00.000Z",
    updatedAt: "2026-04-20T09:20:00.000Z",
    status: "active",
    verified: false,
  },
  {
    id: "demo-vol-dr-niyati-menon",
    role: "volunteer",
    userId: "demo-user-niyati-menon",
    name: "Dr. Niyati Menon",
    roleTitle: "Doctor",
    email: "niyati.menon.demo@example.org",
    phone: "+91 91000 20002",
    city: "Aluva",
    location: {
      lat: 10.1131,
      lng: 76.3438,
      address: "Community clinic lane, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    skills: ["doctor", "triage", "first-aid", "public health"],
    assets: ["medical kit", "car"],
    languages: ["Malayalam", "English"],
    availability: "available_now",
    availableTime: "Rapid deploy for next 24 hours",
    emergencyAvailable: true,
    emergencyRadiusKm: 35,
    distanceKm: 2.9,
    responseRate: "97%",
    completedTasks: 6,
    createdAt: "2026-03-28T11:30:00.000Z",
    updatedAt: "2026-04-20T08:40:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-vol-bineesh-varghese",
    role: "volunteer",
    userId: "demo-user-bineesh-varghese",
    name: "Bineesh Varghese",
    roleTitle: "Boat owner and fisherman",
    email: "bineesh.varghese.demo@example.org",
    phone: "+91 91000 20003",
    city: "Aluva",
    location: {
      lat: 10.1152,
      lng: 76.3443,
      address: "Riverside fisheries jetty, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    skills: ["boat handling", "water rescue", "local river navigation"],
    assets: ["boat", "life jackets"],
    languages: ["Malayalam", "English"],
    availability: "available_now",
    availableTime: "Available during flood alert windows",
    emergencyAvailable: true,
    emergencyRadiusKm: 22,
    distanceKm: 2.1,
    responseRate: "94%",
    completedTasks: 5,
    createdAt: "2026-03-26T06:50:00.000Z",
    updatedAt: "2026-04-20T08:32:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-vol-karan-thakur",
    role: "volunteer",
    userId: "demo-user-karan-thakur",
    name: "Karan Thakur",
    roleTitle: "Off-road vehicle owner",
    email: "karan.thakur.demo@example.org",
    phone: "+91 91000 20004",
    city: "Mandi",
    location: {
      lat: 31.7098,
      lng: 76.9288,
      address: "Terrain support garage, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    skills: ["terrain driving", "evacuation logistics", "local guidance"],
    assets: ["4x4 vehicle", "rope kit"],
    languages: ["Hindi", "Pahari"],
    availability: "scheduled",
    availableTime: "Today until 9 PM",
    emergencyAvailable: true,
    emergencyRadiusKm: 30,
    distanceKm: 3.6,
    responseRate: "91%",
    completedTasks: 4,
    createdAt: "2026-03-24T08:10:00.000Z",
    updatedAt: "2026-04-20T07:55:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-vol-sana-qureshi",
    role: "volunteer",
    userId: "demo-user-sana-qureshi",
    name: "Sana Qureshi",
    roleTitle: "Food donor",
    email: "sana.qureshi.demo@example.org",
    phone: "+91 91000 20005",
    city: "Lucknow",
    location: {
      lat: 26.8924,
      lng: 80.9561,
      address: "Community kitchen lane, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    skills: ["community kitchen coordination", "ration packing"],
    assets: ["pickup truck"],
    languages: ["Hindi", "Urdu", "English"],
    availability: "limited",
    availableTime: "Evenings after 5 PM",
    emergencyAvailable: false,
    emergencyRadiusKm: 16,
    distanceKm: 2.8,
    responseRate: "83%",
    completedTasks: 1,
    createdAt: "2026-04-02T13:00:00.000Z",
    updatedAt: "2026-04-19T18:45:00.000Z",
    status: "active",
    verified: false,
  },
  {
    id: "demo-vol-devika-arora",
    role: "volunteer",
    userId: "demo-user-devika-arora",
    name: "Devika Arora",
    roleTitle: "Shelter provider",
    email: "devika.arora.demo@example.org",
    phone: "+91 91000 20006",
    city: "Lucknow",
    location: {
      lat: 26.8942,
      lng: 80.9476,
      address: "Transit guesthouse block, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    skills: ["temporary shelter coordination", "family intake"],
    assets: ["shelter space", "generator"],
    languages: ["Hindi", "English"],
    availability: "scheduled",
    availableTime: "Beds ready through this week",
    emergencyAvailable: true,
    emergencyRadiusKm: 20,
    distanceKm: 3.1,
    responseRate: "86%",
    completedTasks: 3,
    createdAt: "2026-03-31T15:20:00.000Z",
    updatedAt: "2026-04-20T07:40:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-vol-rohan-singh",
    role: "volunteer",
    userId: "demo-user-rohan-singh",
    name: "Rohan Singh",
    roleTitle: "First-aid volunteer",
    email: "rohan.singh.demo@example.org",
    phone: "+91 91000 20007",
    city: "Lucknow",
    location: {
      lat: 26.8853,
      lng: 80.9514,
      address: "Volunteer base near Polytechnic, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    skills: ["first-aid", "triage support", "camp support"],
    assets: ["medical kit", "bike"],
    languages: ["Hindi", "English"],
    availability: "available_now",
    availableTime: "On-call today",
    emergencyAvailable: true,
    emergencyRadiusKm: 24,
    distanceKm: 1.9,
    responseRate: "93%",
    completedTasks: 4,
    createdAt: "2026-03-29T09:40:00.000Z",
    updatedAt: "2026-04-20T09:05:00.000Z",
    status: "active",
    verified: true,
  },
];

export const demoDonorProfiles: DonorProfile[] = [
  {
    id: "demo-donor-freshplate-foods",
    name: "FreshPlate Foods Foundation",
    email: "support@freshplate-demo.org",
    phone: "+91 92000 30001",
    helpTypes: ["food"],
    preferredSupportAreas: ["community kitchens", "dry ration", "camp meals"],
    totalPledges: 3,
    location: {
      lat: 26.8924,
      lng: 80.9561,
      address: "FreshPlate kitchen depot, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    createdAt: "2026-04-05T10:15:00.000Z",
    updatedAt: "2026-04-20T09:10:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-donor-aangan-stay",
    name: "Aangan Stay Network",
    email: "care@aanganstay-demo.org",
    phone: "+91 92000 30002",
    helpTypes: ["shelter", "clothes"],
    preferredSupportAreas: ["temporary shelters", "family lodging", "blanket support"],
    totalPledges: 2,
    location: {
      lat: 26.8942,
      lng: 80.9476,
      address: "Aangan guesthouse cluster, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    createdAt: "2026-04-05T12:40:00.000Z",
    updatedAt: "2026-04-20T08:55:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-donor-bluecurrent-fishers",
    name: "Blue Current Fishers Cooperative",
    email: "dispatch@bluecurrent-demo.org",
    phone: "+91 92000 30003",
    helpTypes: ["boat", "food"],
    preferredSupportAreas: ["rescue boats", "river navigation", "dry food drops"],
    totalPledges: 2,
    location: {
      lat: 10.1152,
      lng: 76.3443,
      address: "Blue Current jetty, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    createdAt: "2026-04-04T08:00:00.000Z",
    updatedAt: "2026-04-20T08:32:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-donor-lifeline-pharma",
    name: "Lifeline Pharma Circle",
    email: "relief@lifelinepharma-demo.org",
    phone: "+91 92000 30004",
    helpTypes: ["medicine"],
    preferredSupportAreas: ["ORS", "medical kits", "triage supplies"],
    totalPledges: 2,
    location: {
      lat: 10.1131,
      lng: 76.3438,
      address: "Lifeline medical depot, Kochi",
      city: "Kochi",
      state: "Kerala",
    },
    createdAt: "2026-04-03T09:45:00.000Z",
    updatedAt: "2026-04-20T08:42:00.000Z",
    status: "active",
    verified: true,
  },
  {
    id: "demo-donor-highland-4x4-club",
    name: "Highland 4x4 Club",
    email: "ops@highland4x4-demo.org",
    phone: "+91 92000 30005",
    helpTypes: ["vehicle", "other"],
    preferredSupportAreas: ["off-road access", "terrain transport", "rope support"],
    totalPledges: 2,
    location: {
      lat: 31.7098,
      lng: 76.9288,
      address: "Highland garage yard, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    createdAt: "2026-04-02T07:35:00.000Z",
    updatedAt: "2026-04-20T07:58:00.000Z",
    status: "active",
    verified: true,
  },
];

export const demoResourceNeeds: ResourceNeed[] = [
  {
    id: "demo-need-fire-food",
    crisisId: "demo-vikas-nagar-fire-relief",
    label: "Food packets",
    category: "food packets",
    location: {
      lat: 26.8907,
      lng: 80.9608,
      address: "Camp kitchen tent, Vikas Nagar",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    locationLabel: "Camp kitchen tent, Vikas Nagar",
    quantityNeeded: 650,
    quantityPledged: 260,
    urgency: "critical",
    deadline: "Tonight",
    providerHint: "Community kitchens and verified meal donors",
    createdAt: "2026-04-19T07:20:00.000Z",
    updatedAt: "2026-04-20T09:15:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-fire-shelter",
    crisisId: "demo-vikas-nagar-fire-relief",
    label: "Shelter kits",
    category: "shelter",
    location: {
      lat: 26.8919,
      lng: 80.9615,
      address: "Transit shelter line, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    locationLabel: "Transit shelter line, Lucknow",
    quantityNeeded: 150,
    quantityPledged: 70,
    urgency: "high",
    deadline: "Within 24 hours",
    providerHint: "Guesthouses, hostels, and bedding support donors",
    createdAt: "2026-04-19T08:05:00.000Z",
    updatedAt: "2026-04-20T09:05:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-fire-medicine",
    crisisId: "demo-vikas-nagar-fire-relief",
    label: "Medicine kits",
    category: "medicine",
    location: {
      lat: 26.892,
      lng: 80.9588,
      address: "Clinic support corridor, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    locationLabel: "Clinic support corridor, Lucknow",
    quantityNeeded: 220,
    quantityPledged: 120,
    urgency: "high",
    deadline: "Today",
    providerHint: "Medical stores and clinic partners",
    createdAt: "2026-04-19T09:10:00.000Z",
    updatedAt: "2026-04-20T08:58:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-flood-boats",
    crisisId: "demo-kerala-flood-relief",
    label: "Rescue boats",
    category: "boat",
    location: {
      lat: 10.1115,
      lng: 76.3484,
      address: "River response jetty, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    locationLabel: "River response jetty, Aluva",
    quantityNeeded: 5,
    quantityPledged: 3,
    urgency: "critical",
    deadline: "Immediate",
    providerHint: "Boat owners and fisheries cooperatives",
    createdAt: "2026-04-18T16:10:00.000Z",
    updatedAt: "2026-04-20T08:30:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-flood-ors",
    crisisId: "demo-kerala-flood-relief",
    label: "ORS and medicine packs",
    category: "medicine",
    location: {
      lat: 10.112,
      lng: 76.3471,
      address: "Flood health station, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    locationLabel: "Flood health station, Aluva",
    quantityNeeded: 480,
    quantityPledged: 240,
    urgency: "critical",
    deadline: "Within 8 hours",
    providerHint: "Pharmacy partners and public health suppliers",
    createdAt: "2026-04-18T17:00:00.000Z",
    updatedAt: "2026-04-20T08:42:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-flood-shelter",
    crisisId: "demo-kerala-flood-relief",
    label: "Temporary shelter units",
    category: "shelter",
    location: {
      lat: 10.1108,
      lng: 76.3479,
      address: "School shelter cluster, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    locationLabel: "School shelter cluster, Aluva",
    quantityNeeded: 180,
    quantityPledged: 60,
    urgency: "high",
    deadline: "By evening",
    providerHint: "Schools, community halls, and camp infrastructure donors",
    createdAt: "2026-04-18T17:35:00.000Z",
    updatedAt: "2026-04-20T08:52:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-landslide-vehicles",
    crisisId: "demo-hill-landslide-relief",
    label: "4x4 transport slots",
    category: "vehicle",
    location: {
      lat: 31.7122,
      lng: 76.9318,
      address: "Upper road relay point, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    locationLabel: "Upper road relay point, Mandi",
    quantityNeeded: 14,
    quantityPledged: 5,
    urgency: "high",
    deadline: "Tomorrow morning",
    providerHint: "4x4 owners and medical transport crews",
    createdAt: "2026-04-18T06:10:00.000Z",
    updatedAt: "2026-04-20T08:00:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-landslide-ropes",
    crisisId: "demo-hill-landslide-relief",
    label: "Rescue rope kits",
    category: "other",
    location: {
      lat: 31.7127,
      lng: 76.9313,
      address: "Slope access checkpoint, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    locationLabel: "Slope access checkpoint, Mandi",
    quantityNeeded: 30,
    quantityPledged: 18,
    urgency: "high",
    deadline: "Today",
    providerHint: "Mountain clubs and terrain rescue teams",
    createdAt: "2026-04-18T06:35:00.000Z",
    updatedAt: "2026-04-20T08:05:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
  {
    id: "demo-need-landslide-firstaid",
    crisisId: "demo-hill-landslide-relief",
    label: "First-aid kits",
    category: "medicine",
    location: {
      lat: 31.7131,
      lng: 76.9309,
      address: "Medical relay cabin, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    locationLabel: "Medical relay cabin, Mandi",
    quantityNeeded: 90,
    quantityPledged: 32,
    urgency: "moderate",
    deadline: "Within 24 hours",
    providerHint: "Medical supply donors and clinic partners",
    createdAt: "2026-04-18T07:00:00.000Z",
    updatedAt: "2026-04-20T08:08:00.000Z",
    status: "partially-fulfilled",
    verified: true,
  },
];

export const demoResourcePledges: ResourcePledge[] = [
  {
    id: "demo-pledge-fire-food-001",
    crisisId: "demo-vikas-nagar-fire-relief",
    resourceNeedId: "demo-need-fire-food",
    donorId: "demo-donor-freshplate-foods",
    itemType: "food packets",
    quantity: 260,
    note: "Packed meals and dry ration for same-day distribution.",
    location: {
      lat: 26.8924,
      lng: 80.9561,
      address: "FreshPlate kitchen depot, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    createdAt: "2026-04-19T12:10:00.000Z",
    updatedAt: "2026-04-20T09:12:00.000Z",
    status: "verified",
    verified: true,
  },
  {
    id: "demo-pledge-fire-shelter-001",
    crisisId: "demo-vikas-nagar-fire-relief",
    resourceNeedId: "demo-need-fire-shelter",
    donorId: "demo-donor-aangan-stay",
    itemType: "shelter kits",
    quantity: 70,
    note: "Mats, blankets, and temporary lodging support.",
    location: {
      lat: 26.8942,
      lng: 80.9476,
      address: "Aangan guesthouse cluster, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    createdAt: "2026-04-19T16:20:00.000Z",
    updatedAt: "2026-04-20T09:05:00.000Z",
    status: "verified",
    verified: true,
  },
  {
    id: "demo-pledge-fire-medicine-001",
    crisisId: "demo-vikas-nagar-fire-relief",
    resourceNeedId: "demo-need-fire-medicine",
    donorId: "demo-donor-lifeline-pharma",
    itemType: "medicine kits",
    quantity: 120,
    note: "Burn dressing kits and essential medicines.",
    location: {
      lat: 10.1131,
      lng: 76.3438,
      address: "Lifeline medical depot, Kochi",
      city: "Kochi",
      state: "Kerala",
    },
    createdAt: "2026-04-19T18:10:00.000Z",
    updatedAt: "2026-04-20T08:58:00.000Z",
    status: "fulfilled",
    verified: true,
  },
  {
    id: "demo-pledge-flood-boats-001",
    crisisId: "demo-kerala-flood-relief",
    resourceNeedId: "demo-need-flood-boats",
    donorId: "demo-donor-bluecurrent-fishers",
    itemType: "rescue boats",
    quantity: 3,
    note: "Three crewed boats with life jackets for supervised rescue support.",
    location: {
      lat: 10.1152,
      lng: 76.3443,
      address: "Blue Current jetty, Aluva",
      city: "Aluva",
      state: "Kerala",
    },
    createdAt: "2026-04-19T07:20:00.000Z",
    updatedAt: "2026-04-20T08:30:00.000Z",
    status: "verified",
    verified: true,
  },
  {
    id: "demo-pledge-flood-medicine-001",
    crisisId: "demo-kerala-flood-relief",
    resourceNeedId: "demo-need-flood-ors",
    donorId: "demo-donor-lifeline-pharma",
    itemType: "ORS and medicine packs",
    quantity: 240,
    note: "ORS, fever medicine, and essential relief pharmacy supplies.",
    location: {
      lat: 10.1131,
      lng: 76.3438,
      address: "Lifeline medical depot, Kochi",
      city: "Kochi",
      state: "Kerala",
    },
    createdAt: "2026-04-19T10:45:00.000Z",
    updatedAt: "2026-04-20T08:42:00.000Z",
    status: "fulfilled",
    verified: true,
  },
  {
    id: "demo-pledge-flood-shelter-001",
    crisisId: "demo-kerala-flood-relief",
    resourceNeedId: "demo-need-flood-shelter",
    donorId: "demo-donor-aangan-stay",
    itemType: "temporary shelter units",
    quantity: 60,
    note: "Foldable partitions, bedding, and camp setup support.",
    location: {
      lat: 26.8942,
      lng: 80.9476,
      address: "Aangan guesthouse cluster, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
    },
    createdAt: "2026-04-19T20:05:00.000Z",
    updatedAt: "2026-04-20T08:52:00.000Z",
    status: "pending",
    verified: false,
  },
  {
    id: "demo-pledge-landslide-vehicles-001",
    crisisId: "demo-hill-landslide-relief",
    resourceNeedId: "demo-need-landslide-vehicles",
    donorId: "demo-donor-highland-4x4-club",
    itemType: "4x4 transport slots",
    quantity: 5,
    note: "Off-road vehicles available for supervised medical relay.",
    location: {
      lat: 31.7098,
      lng: 76.9288,
      address: "Highland garage yard, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    createdAt: "2026-04-19T06:40:00.000Z",
    updatedAt: "2026-04-20T08:00:00.000Z",
    status: "verified",
    verified: true,
  },
  {
    id: "demo-pledge-landslide-ropes-001",
    crisisId: "demo-hill-landslide-relief",
    resourceNeedId: "demo-need-landslide-ropes",
    donorId: "demo-donor-highland-4x4-club",
    itemType: "rescue rope kits",
    quantity: 18,
    note: "Terrain rope kits and anchoring hardware.",
    location: {
      lat: 31.7098,
      lng: 76.9288,
      address: "Highland garage yard, Mandi",
      city: "Mandi",
      state: "Himachal Pradesh",
    },
    createdAt: "2026-04-19T07:25:00.000Z",
    updatedAt: "2026-04-20T08:05:00.000Z",
    status: "verified",
    verified: true,
  },
  {
    id: "demo-pledge-landslide-firstaid-001",
    crisisId: "demo-hill-landslide-relief",
    resourceNeedId: "demo-need-landslide-firstaid",
    donorId: "demo-donor-lifeline-pharma",
    itemType: "first-aid kits",
    quantity: 32,
    note: "Field first-aid kits for slope relay teams.",
    location: {
      lat: 10.1131,
      lng: 76.3438,
      address: "Lifeline medical depot, Kochi",
      city: "Kochi",
      state: "Kerala",
    },
    createdAt: "2026-04-19T09:30:00.000Z",
    updatedAt: "2026-04-20T08:08:00.000Z",
    status: "pending",
    verified: false,
  },
];

export const demoData = {
  crises: demoCrises,
  ngos: demoNGOProfiles,
  volunteers: demoVolunteerProfiles,
  donors: demoDonorProfiles,
  resourceNeeds: demoResourceNeeds,
  resourcePledges: demoResourcePledges,
};

export function getDemoData() {
  return demoData;
}
